[package]
name = "tenx"
version = "0.1.0"
authors = ["Kyle Hargraves <pd@krh.me>"]

[dependencies]
rand = "*"
lazy_static = "0.1.*"
itertools = "0.5.*"
futures = "0.1.*"
futures-cpupool = "0.1.*"

[profile.release]
debug = true
