[package]
name = "tenx"
version = "0.1.0"
authors = ["Kyle Hargraves <pd@krh.me>"]

[dependencies]
rand = "*"
lazy_static = "0.1.*"
itertools = "0.4.*"
rayon = "0.4.*"

[profile.release]
debug = true
